name: Update CISA Vulnerabilities README

on:
  schedule:
    - cron: '30 20 * * *'  # Run every day at 1:30 am (adjust as needed)
  workflow_dispatch:  # Add a manual run button

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests PyGithub

      - name: Run script to update README
        env:
          CISA_10: ${{ secrets.CISA_10 }}  # Use the GitHub secret for the token
        run: |
          python update_cisa_vulnerabilities_readme.py
